### ISSUE TITLE
Only taking a single optimization step?

### ISSUE THREAD

**Issue by JonathanRayner** [thepowerfuldeez/null-text-inversion#2]
It looks like you're only taking a single optimization step per latent, while the paper suggests 10 steps for each of the 50 diffusion steps ([Appendix D](https://arxiv.org/pdf/2211.09794.pdf)). Is this intentional?

**Comment by thepowerfuldeez** [comment]
you’re right! Good catch
I had problems with multiple backwards initially, but now I have fixed that.
I will update code soon

**Comment by RayleighChen** [comment]
> you’re right! Good catch I had problems with multiple backwards initially, but now I have fixed that. I will update code soon

hi, @thepowerfuldeez.  Good job!
